### ISSUE TITLE
Handling of external mDNS queries

### ISSUE THREAD

**Issue by youennf** [rtcweb-wg/mdns-ice-candidates#117]
mDNS queries triggering responses being sent out of the local link can pose security issues.
We might want to describe the threats and mitigations to use.

**Comment by youennf** [comment]
I do not remember exactly what we were trying to cover here.
@tQsW, @juberti, any thoughts?

**Comment by juberti** [comment]
I think the concern here was around an endpoint responding to mDNS queries from an external (not LAN) client who sent a unicast query to the endpoint's mDNS port, possibly for well-known mDNS names.

**Comment by juberti** [comment]
See also https://github.com/rtcweb-wg/mdns-ice-candidates/pull/111/commits/f658677b623af867f3bfcf02fcec9e16eebf3471

**Comment by youennf** [comment]
Right, the question is whether this additional guideline is specific to ICE Agents registering mDNS names (in which case we should add some wording in this spec) or to all agents registering mDNS names (in which case this might be better handled by the mDNS spec.

**Comment by juberti** [comment]
Right. In thinking about it, it's not clear to me that we're opening up any new attack surface here; mDNS queries sent to our WebRTC ports will be ignored. And we've already given guidance regarding resolution of attacker-supplied names. So I think we can leave this for some other spec.

Note that the security section says implementations "may decide to not" resolve names other than uuid.local, whereas the actual algorithm section says SHOULD NOT.

**Comment by youennf** [comment]
OK, let's close this issue for now.

> Note that the security section says implementations "may decide to not" resolve names other than uuid.local, whereas the actual algorithm section says SHOULD NOT.

Will try clarifying this.
