### ISSUE TITLE
Clarify the definition of "remote mDNS candidate" in "Interactions With TURN Servers"

### ISSUE THREAD

**Issue by tQsW** [rtcweb-wg/mdns-ice-candidates#120]
It is required not to pair local relay candidates with remote mDNS candidates to avoid the leak via CreatePermission requests. As Phillip points in this issue (https://bugs.chromium.org/p/webrtc/issues/detail?id=11038), an ICE agent should not rely on the candidate type field in a hostname candidate to reinforce this constraint. The a=candidate line in signaling can be modified to inject an arbitrary type. Suggest that we clarify the remote mDNS candidates include all hostname candidates with the .local pseudo-TLD.

**Comment by juberti** [comment]
Seems reasonable. The text does not restrict to "typ host", but being extra specific here would still be a good idea.

Phillip also points out that we may want to do this for all DNS names, to prevent the browser from becoming a roundabout DNS resolver, but that is probably outside the scope of this document.
