### ISSUE TITLE
Add note indicating that remote mDNS candidates MUST NOT be resolved if the application is only using local TURN candidates.

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/mdns-ice-candidates#122]
See https://github.com/w3c/webrtc-pc/issues/2533 for details

**Comment by youennf** [comment]
I added a step where we ignore the candidate in that case.
The term 'ignore' should probable be refined as it is used both here and in the context of https://github.com/rtcweb-wg/mdns-ice-candidates/issues/121.
We might want to update ignore in https://github.com/rtcweb-wg/mdns-ice-candidates/issues/121 context.
