### ISSUE TITLE
Using non-RFC6890 compliant IPv4 addresses in examples

### ISSUE THREAD

**Issue by jeroendeb** [rtcweb-wg/mdns-ice-candidates#49]
There is a range of IP addresses set aside for documentation/example purposes 

A. For IPv4 these are 192.0.2.0/24 (see [RFC3330] (IANA, “Special-Use IPv4 Addresses,” September 2002.)).
B. For IPv6 these are 2001:DB8::/32 (see [RFC3849] (Huston, G., Lord, A., and P. Smith, “IPv6 Address Prefix Reserved for Documentation,” July 2004.)).

**Comment by juberti** [comment]
See #69
