### ISSUE TITLE
Autogenerate latest HTML and remove .html file from repo

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/mdns-ice-candidates#53]
Similar to the CI Bot for JSEP: https://github.com/rtcweb-wg/jsep/commit/5be5220549ec06865b183c6c46c98a37c02373b0

**Comment by juberti** [comment]
@youennf, you'll need to set up Travis for this repo, and follow the steps in 
https://github.com/martinthomson/i-d-template/blob/master/doc/REPO.md#automatic-update-for-editors-copy.

Also, worth considering whether this repo should move to the rtcweb-wg org: https://github.com/rtcweb-wg

**Comment by juberti** [comment]
@youennf, thoughts on this?

**Comment by youennf** [comment]
> @youennf, you'll need to set up Travis for this repo, and follow the steps in
> https://github.com/martinthomson/i-d-template/blob/master/doc/REPO.md#automatic-update-for-editors-copy.

Will do.

> Also, worth considering whether this repo should move to the rtcweb-wg org: https://github.com/rtcweb-wg

I think it would be best to have this document in a more neutral place.
rtcweb-wg seems fine, I just wonder what would happen if the document ends up moving in ICE WG.
Maybe this is not a big deal.

**Comment by juberti** [comment]
This is now set up and working.
