### ISSUE TITLE
Should we mention DNS SD work to extend MDNS resolution outside the local link

### ISSUE THREAD

**Issue by youennf** [rtcweb-wg/mdns-ice-candidates#64]
https://tools.ietf.org/html/draft-ietf-dnssd-mdns-relay and related https://tools.ietf.org/html/draft-ietf-dnssd-hybrid define a way to query mDNS outside the local link.
We might want to refer to these techniques in the draft as a way to improve ICE connectivity.

**Comment by juberti** [comment]
Sounds like a good idea - probably mention this in the limitations section where we talk about this problem.

**Comment by tQsW** [comment]
By "outside the local link" do we still assume the reachable network by mDNS is managed? I feel this topic would call for more security consideration accordingly, given that there is no authentication of mDNS messages in the use case proposed. There is an implicit assumption that we trust the local link by default without additional security measure for mDNS. Thoughts?

**Comment by youennf** [comment]
Closing for now.
We can reopen it if there is more interest in the future.
