### ISSUE TITLE
Should we move examples section?

### ISSUE THREAD

**Issue by youennf** [rtcweb-wg/mdns-ice-candidates#74]
Currently it is between limitations and privacy.
I would tend to put it either just after section 3 as a way to describe it or inside section 6.1 since currently the examples mostly show section 6.1 issue.
Another approach would be to inline them where most appropriate.

**Comment by tQsW** [comment]
Yeah, I feel it reads better if placed after the Privacy section where the prflx candidate issue is detailed, or at least that part needs to refer to the example. We may also add examples for scenarios of attacks later. If we do so, we could either 1) place them in the same section as the last one before IANA consideration, referred by corresponding sections or 2) if it grows too big, inline the examples where they immediately demonstrate the case.
