### ISSUE TITLE
Purpose of document: extend ip-handling, or focus on defining the mDNS technique?

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/mdns-ice-candidates#8]
IOW, should this document define the new modes, or just how mDNS should be used to hide local IP addresses? If the latter, we would then also need to write a ip-handling v2 that defined the new modes, and pointed at this doc for details on how the technique should work.

**Comment by youennf** [comment]
From last meeting discussions, the plan was to define the new modes in this document and add a note in the ip-handling document that new modes might be defined with an informative reference to this document.

I think defining the new modes in this document will also ease the authoring work and the review from the RTCWeb WG.

In the long run, I think an ip-handling v2 might be a better place for the definition of the modes.
For instance the guidelines around a default mode does belong in the ip-handling document, not the mdns-ice-candidate document.

**Comment by juberti** [comment]
OK. This particular document may be in the wrong WG then, but we can leave those details for later.

**Comment by juberti** [comment]
Leaving this open to cull the Specification Requirements section once it has been fully incorporated into ip-mdns-ext.
