### ISSUE TITLE
Reduced Connectivity: Mention throughput

### ISSUE THREAD

**Issue by lgrahl** [rtcweb-wg/mdns-ice-candidates#83]
> When mDNS fails, ICE will attempt to fall back to either NAT hairpin, if supported, or TURN relay, if not. As noted in {{IPHandling}}, this may result in increased media latency and reduced connectivity/increased cost (depending on whether the application chooses to use TURN).

Let's also consider data use cases here: Fallback to TURN has a severe effect on throughput in many cases.

**Comment by juberti** [comment]
Sure, could add a brief note on this.

**Comment by juberti** [comment]
The text here isn't normative, so I don't think we need to have a lengthy discussion of this - a few words should suffice.

**Comment by juberti** [comment]
Fixed by #101
