### ISSUE TITLE
Scope to communication peer

### ISSUE THREAD

**Issue by martinthomson** [rtcweb-wg/mdns-ice-candidates#84]
For WebRTC, this should be scoped to the RTCPeerConnection instance.

**Comment by juberti** [comment]
Explain, please.

**Comment by juberti** [comment]
Seeing this in the notes:

> Martin: I think we want scope on communication peer; in browser this matches origin.  Two entities we want to conceal identity from, web app and application peer.
> 
> David Schinazi (chair of DNS-SD): Can you please post your draft on DNS-SD mailing list?
> Youenn: sure
> 
> Tim Panton: I don't see any downside to making scope to peer connection instance.
> Martin Thomson: I agree.
> Youenn: Page can open tens of thousands of peer connections.  Would flood mDNS.
> Martin: We already have this problem with STUN/TURN, I would throw this in the same rate limit bucket.
> 
> Martin: Do you have to announce that you have a name, or could you just respond to queries?
> Stuart: In theory you could, but would require changes to APIs.
> 
> EKR: Agree these should be scoped to PC.

Need to think about how we can do this without increasing gathering latency and/or network stress (i.e. for mesh applications with many PCs).

**Comment by juberti** [comment]
Note that MSID already provides a correlation surface to the peer, as do IPv6 addresses.

**Comment by youennf** [comment]
This seems to give some small benefits in terms of privacy but I would constraint this on the ability to not probe the network/advertise names.

Another possibility would be to scope the mDNS name by peerIdentity in addition to origin.

**Comment by martinthomson** [comment]
The problem with peerIdentity is that we aren't seeing a lot of use of that in existing applications.

For those that want to maintain unlinkability when they aren't using peerIdentity, we could provide a control that allowed them to generate a new value, but I would prefer to ensure privacy by default.

Yes, this makes the concerns around denial of service from broadcast messages somewhat worse, but legitimate uses of RTCPeerConnection use them at a sufficiently low rate that I am not concerned about that.

We could create a control, much like RTCCertificate, that would allow sites to opt in to linkability (non-private by explicit choice), but that would be complex.

**Comment by juberti** [comment]
Plan is to add some more discussion on the tradeoffs here (e.g. latency for call setup, need for rate limiting)

**Comment by youennf** [comment]
> For WebRTC, this should be scoped to the RTCPeerConnection instance.

I wonder what are the exact benefits compared to a browser context scope.

Let's consider a user A talking to user B and user C on the same page.
Users B and C can then infer they are talking to the same user A using the MDNS ICE candidate.

If user B and user C are native, they can infer the same information from IP addresses.
MDNS ICE candidate is not creating any additional risk.

In the case user B and C are using web pages, these web pages are probably run by the same site. It would mean the web site is voluntarily leaking that info. In that case, MDNS ICE candidate is not creating any additional risk.

If user B and C are using web pages from other domains, the web page from user A is communicating to the web pages from B and C. There is a trust relationship between the various pages. It is true that MDNS ICE candidates provide IDs. Chances are high that some other browser context persistent IDs are provided anyway, like names, to enable users to access calls.
I think it is the responsibility of user A web page to not leak these IDs if there is such an expectation.
The web page can easily do so by creating as much iframes as different MDNS ICE candidates are needed and partition the persistent IDs accordingly.

I am not convinced that browsing context vs. peer connection object changes things much in practice.
I can see some bigger differences between origin vs. browsing context or page vs. browsing context.

**Comment by juberti** [comment]
I agree with this overall. If you really don't want correlation, I think you need to use TURN. Otherwise the caller's STUN IP will typically be good enough for correlation, even for a web client or a network eavesdropper.

Plus I think that there are other correlation surfaces by default, e.g. a=msid.

**Comment by youennf** [comment]
I think we have consensus here. The current guidelines in the spec say:
`In the case of a web application, the use of registered mDNS hostnames SHOULD be scoped by the web application origin, and SHOULD have the lifetime of the page executing the web application.`

It could be further tightened if we want to refer to HTML concepts.
Looking at implementations, they defer a bit but the behavior is the same for separate pages as well as third-party iframes.

@martinthomson, please let me know if you would like tighter wording.
Closing for now.
