### ISSUE TITLE
Require a global rate limit on mdns queries

### ISSUE THREAD

**Issue by martinthomson** [rtcweb-wg/mdns-ice-candidates#86]
Querying for mdns names could be used to flood the network with broadcast messages.  We need to rate limit those globally.  Maybe add a lower limit by origin so that we don't have origins deny service to other origins.

**Comment by martinthomson** [comment]
Lgtm. In practice you might want to prioritize the messages that release names, or even reserve slots for those but I don't think that needs text.

Is there a rate we can recommend?

**Comment by jeroendeb** [comment]
We should probably also call out the correct response to exceeding a rate limit: drop the candidate (as apposed to delay the candidate processing).

**Comment by juberti** [comment]
More context from IETF 103:
https://datatracker.ietf.org/doc/minutes-103-rtcweb/

Cullen: I think we should discuss the rate limiting.
Youenn: mDNS implementation rate limits it.
Cullen: What is it?  I think mDNS was not written with the assumption that
hostile drive-by web pages would be doing this. Christer: I thought you said
limit of one per page, but would need two for IPv4/IPv6. Youenn: Yes, one per
IP address. Martin: Rate limiting is analogous to STUN Cullen: No, STUN isn't
multicast Yerunn?? 2 (Google): Thought of creating pool of these Cullen: We
already have similar pool for STUN EKR: I don't see how this fixes rate
limiting Youenn: Limited per top origin EKR: I'll just nav.  Register domains
1-one billion.example.com.  Web security's hard.  Requires more thinking than
I'm getting from this doc. Martin: I'll open an issue on not broadcasting the
name.  Might help on not stressing the network. Cullen: No, doesn't help

Tim Panton: Is .local fully standardized?
Stuart: RFC 6762, recorded in IANA special use domain registry.  Also, networks
don't support mDNS; networks support multicast. Adam: Issues with this would
arise in enterprise, who turn off telemetry, not clear how much we could tell
this Nils: One mDNS per where you fetched your webpage from.  Shouldn't be that
high, but may be. Cullen: We should do flooding analysis and data before we
start experimenting on large corporate networks, this is a congestion control
issue. Stuart: I'm not sure why you're concerned about picking one address. 
Every mac here has one .local name for all its interfaces.  Also, announcements
reduce

**Comment by juberti** [comment]
@tQsW will come up with a suggested global limit. Other than that, existing text is fine.
