### ISSUE TITLE
Move repo to rtcweb-wg org

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/mdns-ice-candidates#87]
Planning on doing this Friday, Nov 9

**Comment by juberti** [comment]
cc @youennf @tQsW @jeroendeb

**Comment by youennf** [comment]
Yep, this makes sense to me.
The RTCWeb WG is planning to be closing at some point (which might mean that this work would go to MMUSIC) but I would think the RTCWeb org to live longer.

**Comment by jeroendeb** [comment]
They said that rtcweb has closed as of Thursday's meeting, that we should
continue our work with mmusic

**Comment by youennf** [comment]
It is also my understanding that the plan is to continue our work in mmusic.
That said, this might also be the case for ip-handling v2 and I think moving to rtcweb-wg is a good move anyway.

**Comment by youennf** [comment]
I tried to do the transfer but I do not have permission to create a repo in rtcweb-wg.
@juberti, can you allow me to create a repo in rtcweb-wg org?

I haven't found a way to make somebody else an owner of this repo.
Maybe multiple owners make only sense for org repos.

**Comment by juberti** [comment]
OK, I added you to rtcweb-wg, give it a shot after you accept the invite.

**Comment by youennf** [comment]
Done. https://github.com/rtcweb-wg/mdns-ice-candidates/pull/89 is doing a minor fix to the readme.
