### ISSUE TITLE
STUN servers can be run inside the enterprise

### ISSUE THREAD

**Issue by jeroendeb** [rtcweb-wg/mdns-ice-candidates#88]
During the rtcweb working group meeting, it was mentioned that a lot of enterprises run STUN servers inside their network.

A degenerate use case? Probably to enable mode 3 browsers / Safari  to make calls within the enterprise, without hairpin NAT or TURN servers?

This would expose local addresses as candidates, by passing mDNS obfuscation.

**Comment by juberti** [comment]
I think this is a non-issue: this requires a non-application-supplied STUN server, and the local administrator can simply disable this if desired.

**Comment by youennf** [comment]
The concern was that a web application would try to contact local network STUN servers, probably by feeding IP addresses as STUN servers in the RTCPeerConnection constructor.

This attack will indeed defeat the purpose of mode 3 and mDNS obfuscation.
This seems like a more general issue to me than mDNS ICE candidates.
I haven't looked at whether some IETF documents are already discussing this particular issue.
It is similar in principle to non local network web pages trying to access resources in a local network.

Ideally, these STUN servers would require some credentials.
Browsers might also want to throttle somehow how much STUN servers can be queried.

**Comment by lgrahl** [comment]
Trying to reach local STUN servers seems like a lot of effort just for the purpose of fingerprinting. It kind of reminds me of my very silly thought experiment to exhaust all available ports in one normal tab by creating dozens of `RTCPeerConnection` instances and then trying to create one more `RTCPeerConnection` in a private tab. If it doesn't work, you know that you're on the same machine.

Or do you see another attack scenario?

**Comment by jeroendeb** [comment]
@lgrahl My concern with local STUN servers is that host candidates will become srflx candidates and would be signaled as such to peers. If this peer is outside of the network, it provides the same fingerprinting capability as-if mDNS wasn't used. If application provided STUN servers and local STUN servers are mutual exclusive there is no issue (this is where I'm unclear).

**Comment by youennf** [comment]
> Trying to reach local STUN servers seems like a lot of effort just for the purpose of fingerprinting.

Agreed, the more costly the fingerprinting, the less likely it will be used in practice.

> If application provided STUN servers and local STUN servers are mutual exclusive there is no issue (this is where I'm unclear).

I do not think they are mutually exclusive.
A web application may either know some valid local STUN servers (regular scenario) or will try to guess (attack scenario).

**Comment by lgrahl** [comment]
I assume what @jeroendeb means is the scenario where the local STUN server is part of the default ICE servers. The STUN server would reflect the private IP and the ICE agent would then present it as a public IP. That would essentially result in the status quo as of today and leak the private IP again.

**Comment by lgrahl** [comment]
To mitigate this, it might make sense to require binding default ICE servers to specific origins (e.g. `*.example.com`). But that's WebRTC spec work. This document could include that aspect to the list of *Privacy Considerations* as it seems addressing this is out of the scope of this document.

**Comment by juberti** [comment]
Agree with @lgrahl's comment; we are talking specifically about http://w3c.github.io/webrtc-pc/#dom-rtcpeerconnection-getdefaulticeservers, rather than the application guessing at the correct local STUN server (which seems difficult to do and is probably a 1% scenario, so unlikely to be seen in practice).

As @lgrahl mentions, binding the default ICE servers to specific origins seems like the right solution; this mechanism is discussed in the spec link noted above, and we should add a corresponding note to this document.

**Comment by youennf** [comment]
I see, in this case, it is more a feature than a bug to me.
As discussed in https://github.com/w3c/webrtc-pc/issues/2023, Firefox has two configuration options:
- A list of browser defined ice servers
- A boolean to either combine or replace web application ice servers with browser defined ice servers
WebKit does not support any of that, I am not sure of other browsers.

> As @lgrahl mentions, binding the default ICE servers to specific origins seems like the right solution; this mechanism is discussed in the spec link noted above, and we should add a corresponding note to this document.

I am not sure this is actually discussed in http://w3c.github.io/webrtc-pc/#dom-rtcpeerconnection-getdefaulticeservers. From my reading of webrtc-pc, it is the exposure of the list of default ice servers that might only be available to some origins. The spec says that the list "is the same across origins".

**Comment by juberti** [comment]
webrtc-pc sayeth:

> This list is likely to be persistent and is the same across origins. It thus increases the fingerprinting surface of the browser. In privacy-sensitive contexts, browsers can consider mitigations such as only providing this data to whitelisted origins (or not providing it at all.)

**Comment by juberti** [comment]
getDefaultIceServers is not widely implemented, and may even be deprecated eventually. We also think this is out of scope for this document.
