### ISSUE TITLE
Consider exposing MDNS ICE candidate with a specific service type

### ISSUE THREAD

**Issue by youennf** [rtcweb-wg/mdns-ice-candidates#90]
Currently, the spec uses MDNS to expose a name/IP address relationship.
It was suggested that alternatively, this could be exposed as a service of a given type (_webrtc._udp for instance).

The advantage I can think of is that we fix https://github.com/rtcweb-wg/mdns-ice-candidates/issues/37 more cleanly: any already existing MDNS service would not be reachable by mDNS ICE candidate except if opting in by registering this particular given type.

**Comment by juberti** [comment]
Would this be a superset of the existing functionality - basically, the uuid name is registered, but with a specific service tag?

**Comment by jeroendeb** [comment]
Adding discovery for mDns candidates would expose end-point's candidates for parties not involved in signalling. Doesn't seem like a good idea, or am I misunderstanding.

Yes, we did a little prototype using mDNS for discovery of signalling en-points (basically enabling WebRTC without a signalling server), but that would require standardization of the signalling protocol.

**Comment by youennf** [comment]
> Would this be a superset of the existing functionality - basically, the uuid name is registered, but with a specific service tag?

Yes, that would be the idea.
At registering time, one would provide a name, a record and a service type.
There is a slight mismatch though: it would also provide a port which we do not care here.

> Adding discovery for mDns candidates would expose end-point's candidates for parties not involved in signalling. Doesn't seem like a good idea, or am I misunderstanding.

Yes, there is a tradeoff here.
On one side, you know for sure that you are talking to somebody that can handle WebRTC.
On the other hand, others in the same network know for sure that you can talk/are talking WebRTC.

**Comment by juberti** [comment]
Discussed and this seems like significant work for minimal gains (since ICE already protects arbitrary machines from receiving unwanted traffic). Plus, tracking is increased.
