### ISSUE TITLE
Define c= attribute in the case of only mDNS candidates

### ISSUE THREAD

**Issue by jeroendeb** [rtcweb-wg/mdns-ice-candidates#91]
Currently it contains:

_c=IN IP4 address/ttl_

Obviously, putting one of the candidate's IP address there would defeat the purpose of use mDNS.

Options:

Can this be omitted?
Should it have a fake IP address of the right address family?
Should it be allowed to have an mDNS name?

**Comment by juberti** [comment]
Just use the mDNS name.

**Comment by juberti** [comment]
If we run into issues, we could use 0.0.0.0:9 as we do when there are no candidates, but that starts to get complicated (i.e. may require updates to other specs)

**Comment by jeroendeb** [comment]
mDNS name with IP4?

**Comment by juberti** [comment]
good point - shouldn't matter that much, but IP4 seems like the safest choice.

**Comment by juberti** [comment]
Agreed to use mDNS + IP4. We'll reevaluate if this causes problems.

**Comment by juberti** [comment]
Fixed by #102

**Comment by tQsW** [comment]
We have observed an interop issue in the experimental deployment. Endpoints can fail to parse the SDP when the c= line contains a FQDN.

> If we run into issues, we could use 0.0.0.0:9 as we do when there are no candidates, but that starts to get complicated (i.e. may require updates to other specs)

This is the current solution.

**Comment by juberti** [comment]
Well, at least we thought of the solution already :)
