### ISSUE TITLE
Define the contingencies when mDNS protection should be enabled/disabled

### ISSUE THREAD

**Issue by tQsW** [rtcweb-wg/mdns-ice-candidates#92]
In the draft, we currently have no clear definition on this aspect. One thought we have is to couple the IP revealing permission with the  getUserMedia permission. This is in alignment with the existing practice of the network enumeration permission in browsers. A separate permission from the user for the IP revealing is the alternative that reduces the implications from a single permission.

**Comment by juberti** [comment]
I think this is outside the scope of this work - it's already addressed in rtcweb-ip-handling.

**Comment by tQsW** [comment]
My concern is the current draft does not provide a precise mapping to modes in rtcweb-ip-handling and the privacy guideline, namely Section 5. We may need the reference to mode 2.1 in ip-handling-ex-mdns, which however delegates the privacy guideline to ip-handling, and meanwhile ip-handling currently has only a brief recommendation after mode 4.  A link feels missing in deriving (transitively) the exact condition in the text. This issue will probably be gone after consolidating the two ip-handling drafts and editing Section 5. Let me know what you think.

**Comment by juberti** [comment]
https://tools.ietf.org/html/draft-uberti-ip-handling-ex-mdns-00#section-3 tries to spell this out, referring back to mdns-ice-candidates. I don't think mdns-ice-candidates should ref ip-handling-ex-mdns; I would prefer that any mode discussion be confined to that document.

**Comment by juberti** [comment]
Discussed and plan is to simply add some text that legacy endpoints are more likely to malfunction with mDNS names (in the same section where we talk about performance/cost downsides)
