### ISSUE TITLE
mDNS names resolving to more than one IP: improve on picking the 'first' IP of an AF

### ISSUE THREAD

**Issue by jeroendeb** [rtcweb-wg/mdns-ice-candidates#93]
From Tom Pusateri:

When more than one IPv4 or more than one IPv6 address is present, it seems like it would be better to first prefer an address that is on a shared network instead of always taking the first one (which doesn’t mean anything in DNS). If you want others to use the same address you should prefer the lowest one or the highest one or something sortable instead of the first one which could be different depending on hashing in a cache.

**Comment by juberti** [comment]
Discussed and agreement was to find a simple alternate algorithm.

**Comment by jeroendeb** [comment]
Closed by PR #108
