### ISSUE TITLE
Clarify 'usable registered mDNS hostname'

### ISSUE THREAD

**Issue by jeroendeb** [rtcweb-wg/mdns-ice-candidates#94]
In the section gather candidates, it says:

"Check whether the ICE agent has a usable registered mDNS hostname resolving to the ICE candidate’s IP address. If one exists, skip ahead to Step 6."

We, maybe, should clarify this refers to a registered mDNS hostname as produce by this spec, not another (possibly meaningful) name created in some other context.

**Comment by juberti** [comment]
Makes sense as an editorial cleanup.

**Comment by juberti** [comment]
Fixed by #103
