### ISSUE TITLE
ice-sip-sdp update

### ISSUE THREAD

**Issue by juberti** [rtcweb-wg/mdns-ice-candidates#98]
Ensure that ice-sip-sdp (S 4.1) has been updated to allow FQDN addresses.

**Comment by youennf** [comment]
What are the next steps here?

**Comment by juberti** [comment]
ice-sip-sdp sayeth:

      <connection-address>:  is taken from RFC 4566 [RFC4566].  It is the
      IP address of the candidate, allowing for IPv4 addresses, IPv6
      addresses, and fully qualified domain names (FQDNs).  When parsing
      this field, an agent can differentiate an IPv4 address and an IPv6
      address by presence of a colon in its value - the presence of a
      colon indicates IPv6.  An agent generating local candidates MUST
      NOT use FQDN addresses.  An agent processing remote candidates
      MUST ignore candidate lines that include candidates with FQDN or
      IP address versions that are not supported or recognized.  **The
      procedures for generation and handling of FQDN candidates, as well
      as, how agents indicate support for such procedures, need to be
      specified in an extension specification.**

Perhaps this spec should explicitly update mmusic-sip-sdp as providing a procedure for handling mDNS FQDN candidates. Probably something for the WG to weigh in on.

**Comment by tQsW** [comment]
The latest guideline from the email thread is to update ICE-SIP-SDP in the mdns-ice-candidates draft.
